### ISSUE TITLE
Chrome styles selects with background-color

### ISSUE THREAD

**Issue by scurker** [daxko/design#38]
Chrome styles selects with a default background color. If you look at the user agent stylesheet you see...

```css
select, input[type="color" i][list] {
  background-color: rgb(248, 248, 248);
}
```

We should implement `background-color` as part of our css so we can at least have consistent styles across all the browsers.

**Chrome**
![screen shot 2015-06-18 at 4 31 33 pm](https://cloud.githubusercontent.com/assets/1062039/8242777/876e43e8-15d7-11e5-8b29-7e59c39349c9.png)
